### ISSUE TITLE
SKIF.exe linux AMD GPU

### ISSUE THREAD

**Issue by Pednick** [SpecialKO/SpecialK#143]
SKIF.exe crashes with this error:
[SKIF_Util_IsHDRActive@1292] DisplayConfigGetDeviceInfo failed: [87] Invalid parameter.

I run on linux with wine and AMD GPU.

**Comment by Aemony** [comment]
Hi,

This is technically the wrong repo, since it's not SK related, but whatever.

When does it crash? On launch? Later?
Can you upload the full logs?

The error message you pasted is not what caused a crash, but it may be the last printed log just before the crash itself.

Also, just FYI that SKIF's usability on Linux is like... none? It is solely an injection service manager that is unsupported on Linux as well as a game launcher that relies on URIs/paths almost certainly inaccessible from the Wine instance it's running in.

On Linux you typically have to install Special K's DLL files (SpecialK32/64.dll) locally in the game folder namned as an injection point (e.g. dxgi.dll) and then configure Wine/Proton/Lutrix/whatever to load the proxy DLL file as well... We don't really have any instructions for how to do so since Linux as a whole is an unsupported platform.

**Comment by Pednick** [comment]
> On launch

On launch, but like you said if it's usability on Linux is none, then I guess there's my answer, thanks anyway. will close this then.
