### ISSUE TITLE
Please create a public changelog for the latest/stable version of Special K

### ISSUE THREAD

**Issue by FlawlessCasual17** [SpecialKO/SpecialK#156]
I am aware there is a file literally called `CHANGELOG.txt`, but that text file contains versions of Special K which are experimental, but not the latest version. Could you please do the following? It would make maintaining the Special K package for Winget/Scoop much easier.

**Comment by Kaldaien** [comment]
That's in the releases section already.
Ironically, people are irritated that the release tag has such a lengthy set of changes 🤷

**Comment by Aemony** [comment]
Use SKIF configured for the Website update channel and then click "release notes" (or what it's called) on the About tab.

That will parse the central repository.json file and filter out all Discord ("experimental") releases and only showcase changes in Website ("stable") releases. These changes are often summarized if they cover longer time skips.

I am not looking forward to the next stable version release since it'll take ages summarize everything and highlight the main points for both SKIF and SK since the last stable release 6 months ago 😩

**Comment by FlawlessCasual17** [comment]
The release section on the **SpecialK** repository show's a previous version, not the latest version, which is `23.9.10.5`.
![image_18](https://github.com/SpecialKO/SpecialK/assets/101912712/36e93938-54e5-48fa-bc61-4bd306551de7)

**Comment by FlawlessCasual17** [comment]
Also, I did some digging on your website and found this file, https://sk-data.special-k.info/repository.json.

Are you okay with me if I run a PowerShell script, or batch script that uses curl to check for the latest version with this file in your website?

**Comment by Aemony** [comment]
> Are you okay with me if I run a PowerShell script, or batch script that uses curl to invoke a web request to this part of your website to check for the latest version?

It's hosted on a CDN so that's fine.

> EDIT: is there something like this but for the 7z archive that contains SKIF.exe?

There isn't since I can't be bothered creating a new complete archive for all experimental releases, so I only push one for the latest stable release (linked from the main website).

Using the installer nowadays is of critical importance since it also applies a few critical changes to the operating system to ensure Special K's full functionality is possible.

**Comment by FlawlessCasual17** [comment]
Okay thanks for letting me know

**Comment by FlawlessCasual17** [comment]
Thank you very much @Aemony and @Kaldaien
