### ISSUE TITLE
Current DXVK implementation (as of 2.3.1) seems to trigger SK_DXGI_PresentBase twice per frame

### ISSUE THREAD

**Issue by Kethen** [SpecialKO/SpecialK#167]
In Wine, when dxvk d3d11.dll+dxgi.dll is installed to c:/windows/system32, SpecialK can still be hooked as local dxgi.dll/d3d11.dll placed next to applications

When loaded that way (SpecialK hooking DXVK d3d11.dll and dxgi.dll), below can be observed:
1. SpecialK actually hooks correctly, I was interested in the texture modding feature and both dumping and injecting were working
2. However Performance is degraded
3. Built in fps counter shows double actual application framerate

While I have not performed any runtime tracing to confirm this, this is likely caused by the fact that dxvk `DxgiSwapChain::Present` just calls `DxgiSwapChain::Present1` with null `pPresentParameters`, firing both `Present` and `Present1` hooks when an application uses `Present`

https://github.com/doitsujin/dxvk/blob/2b70ba8f7798107308a0c34358a9e83e77017dfd/src/dxgi/dxgi_swapchain.cpp#L305-L307

Perhaps a config options should be added to skip either `DxgiSwapChain::Present1` or `DxgiSwapChain::Present` hooking/callback?

**Comment by Kaldaien** [comment]
Ugh.

I was hoping this issue would never come up. Figures it would be DXVK though.

I think the proper solution would be for SK to call `Present1 (...)` in its `Present (...)` hook and never call the original `Present` function. The reason I haven't done this is because there are some overlays that don't understand `Present1`. The Steam overlay was like that for many years.

**Comment by Kaldaien** [comment]
No wait, nevermind. This isn't fixable. The Steam overlay and RTSS will both crash if `Present1 (...)` is called.

This is better addressed if you contact the developers of DXVK instead.
