### ISSUE TITLE
NieR: Automata Frame Rate wont uncap on Proton/Wine

### ISSUE THREAD

**Issue by jolty1** [SpecialKO/SpecialK#195]
Description:

I cannot seem to uncap frame rate on Proton.

![Screenshot_20240730_113200](https://github.com/user-attachments/assets/2664184c-838d-4c46-9e68-ff0bf3e2afdf)

I've tried older version of Proton 7-8-9/SpecialK + Dev version from Discord which crashes, Proton-GE. Installed vcrun2017 into the proton prefix. Tried 120/144 Hz. Disabling Steam overlay/MangoHud encase of it interfereing.

Any advice ? 

Special K works on Hatsune Miku: Project DIVA Mega Mix+  I had no issues unlocking the FPS.

Steps to reproduce:

1. Open SpecialK menu
2. Check Uncap FPS, FPS is still capped to 60.

Thanks.

**Comment by jolty1** [comment]
[dxgi.ini](https://github.com/user-attachments/files/16426692/dxgi.ini.txt)

[FAR.ini](https://github.com/user-attachments/files/16426693/FAR.ini.txt)

Hatsune Miku: Project DIVA Mega Mix+
![Screenshot_20240730_122307](https://github.com/user-attachments/assets/da7d937a-f1a9-48df-b212-a713e2b4e397)

**Comment by Kaldaien** [comment]
This is because QLOC are dummies :)

You are running the Windows 7 version of NieR: Automata because of their install script. That's the original version of the game that SK is no longer compatible with. You need to make sure you run the Windows 8+ version. Probably easier to just grab it off a real Windows machine than screw around with install scripts.

**Comment by jolty1** [comment]
I see, some DXVK shenanigans going on.

doitsujin/dxvk#2691

**Comment by doitsujin** [comment]
Replicant isn't Automata and even for Replicant we ended up removing it because people genuinely seem to prefer everyone having an objectively worse out-of-the-box experience over setting a single environment variable when uisng mods.

The full list of app profiles isn't exactly hidden either. https://github.com/doitsujin/dxvk/blob/master/src/util/config/config.cpp

**Comment by jolty1** [comment]
Like the DXVK dev said it is not capping the fps.

Interesting that the black frame insertion feature in SK allows the frame rate to go above 60 fps. Could this lead to work around ? 

I should mention that lowering the FPS to below 60 then setting to anything above, will actually change it for a fraction of a second.

![Screenshot_20240803_220152](https://github.com/user-attachments/assets/6f55ac75-ca3e-47e5-9df9-3b2a8d909b1c)

**Comment by jolty1** [comment]
Incompatible with Wine.

**Comment by jolty1** [comment]
Incompatible with Wine.

**Comment by Dreamail** [comment]
May I ask if you just give it up? Or you have some way to unlock fps in proton?

**Comment by jolty1** [comment]
I gave up. Someone else managed to do it.. years ago.

On pre 2021 Nier update and  with old version of FAR.

[https://miyacogbf.github.io/mlgb/nier-automata-far/](url)
