### ISSUE TITLE
Dgvoodoo interop isn't detected when SK isn't wrapping dinput8

### ISSUE THREAD

**Issue by mirh** [SpecialKO/SpecialK#56]
I was kinda running out of dlls too hook for medal of honor airborne (crazy how many old things UE3 originally used), when I found d3d11.dll and dxgi.dll still worked. 
`Active Render API` isn't showing "D3D9→11" though, but "D3D11.4".

**Comment by Spodi** [comment]
I don't quite understand when SK fails to show the interop? Does it only show if SK is dinput8.dll and not if its a different name? And what's the name for dgvoodo2 in this case?

**Comment by Aemony** [comment]
`D3D9→11` is a label that only appears if SK detects that the local d3d9.dll file has "dgVoodoo" in its FileDescription field.

https://github.com/SpecialKO/SpecialK/blob/2ce56114156812fade72a2eaad19d378f9a9d553/src/SpecialK.cpp#L874

**Comment by Aemony** [comment]
This for example is Helltaker, a D3D11 only game, which SK reports as `D3D9→11` solely because dgVoodoo's 32-bit D3D9.dll file is present in the game folder. The game doesn't load the DLL file, much less make use of it, but its presence alone has SK think the API is being translated.

![Helltaker 2023-02-18 12_15_06](https://user-images.githubusercontent.com/10578344/219857286-3fd54a7e-fcc5-4d76-89c9-40eda6c047af.png)

**Comment by mirh** [comment]
Of course I'm still talking about a d3d9 game. 
Yes, if I have SK as `d3d11.dll` instead of `dinput8.dll`, it won't detect dgvoodoo anymore. 
I suppose even that helltaker case is kinda worth fixing.

**Comment by mirh** [comment]
I couldn't directly test with MOHA, but it seems fixed elsewhere. 
If helltaker is also good please close.

**Comment by Aemony** [comment]
This should be solved now everywhere, so closing this.
