### ISSUE TITLE
Technical possibility of eliminating scanline sync lag completely

### ISSUE THREAD

**Issue by pbaykalov** [SpecialKO/SpecialK#57]
https://github.com/SpecialKO/SpecialK/blob/1e92f3cb01fe5a0015c7b4b3732dd1fde968cc3a/src/render/d3d9/d3d9.cpp#L1619

Is it possible to call the wait after the present, not before? That would eliminate the lag and make scanline sync basically equal to adaptive sync.

Obvious problems are:  
1) the wait time should predict how long the next frame creation will take on CPU (now only the GPU processing time is an unknown variable and it's adjusted only manually if understand it correctly)  
2) if wait time is predicted incorrectly there will be a lag or a tear depending on what's the direction of miss

How does it sound to you?

**Comment by Kaldaien** [comment]
What?

The code you've highlighted is for the old Low Latency mode.

```cpp
                case limiter_mode_e::LatentSync:
                  config.render.framerate.present_interval   = 0;    // Turn VSYNC -off-
                  config.render.framerate.enforcement_policy = 4;
                  break;
```

Latent Sync uses enforcement_policy 4 and is actually a two-phase limiter; there are waits before and after Present.

CPU idle time is distributed between waiting for the Vertical Blanking period and delaying the beginning of the next frame. The "Delay Bias" option controls this behavior.

The limiter already predicts how long the game's simulation is going to take as well as any overhead observed during Present calls (third-party overlays hook Present and contribute to timing variability, which Latent Sync factors).

In my testing, Latent Sync is already lower latency than VRR at the same framerate (largely because once you hit refresh rate with VRR, VSYNC kicks in and frames start queuing).

**Comment by pbaykalov** [comment]
> On that note, I was reminded by this thread that we don't actually have a proper section for Latent Sync on the wiki yet, so I went ahead and created one with Kal's great summary of the feature as a base: https://wiki.special-k.info/en/Advanced/Video#latent-sync

I hope you highlight the improvements compared to RTSS. Would be nice if Unwinder borrowed them.

**Comment by pbaykalov** [comment]
I wonder why scanline sync is still absent from GPU drivers, it's such a great feature.
