### ISSUE TITLE
I can‘t operate the SpecialK In-game GUI

### ISSUE THREAD

**Issue by Demonese** [SpecialKO/SpecialK#61]
I tried to use SpecialK to monitor my engine, but unfortunately, the in-game GUI don't seem to have received any keyboard or mouse messages.

Unfortunately, I am not familiar with hook technology.

Engine source code: https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/tree/no_win7_win8x

**Comment by Kaldaien** [comment]
I'm looking at your window management code right now and I think you may have misunderstood how window focus works on Windows.

https://github.com/Legacy-LuaSTG-Engine/LuaSTG-Sub/blob/af8f4477fb5fa531551d92072d482bdc8efc1163/LuaSTG/Core/Graphics/Window_Win32.cpp#L43-L60

The focus window should not be confused with the foreground window. They're often the same thing, but if you track the foreground window instead of keyboard focus, there will be situations where your application has keyboard focus but another window is in the foreground.

I'd suggest instead of using the foreground window / window activation, you monitor for `WM_SETFOCUS` and `WM_KILLFOCUS`.

<hr>
That said, SK should be able to get input just fine even if you're not handling window focus properly. The only scenario I can think of is if your engine is using multiple windows, but SK would warn about this.

**Comment by Demonese** [comment]
> I'd suggest instead of using the foreground window / window activation, you monitor for `WM_SETFOCUS` and `WM_KILLFOCUS`.

Thank you for your suggestion.

I'm trying to replace `WM_ACTIVATEAPP` with `WM_SETFOCUS` and `WM_KILLFOCUS`, but it does not work.

I remove the imgui message handler (my engine integrates imgui for debugging), but in-game GUI still doesn't respond to my mouse operation.

I also remove the code for tracking the focus of the window, but the problem still exists. In fact, it is used to detect software that is not written properly. Some software try to get window focus in the background, and then cause the engine to leave the exclusive fullscreen. :(

Is there any other suggestions?

**Comment by Aemony** [comment]
Hopefully you've managed to solve the issues you ran into regarding this stuff. Since Kal doesn't have any more suggestions to give, I'll close this issue ticket since it's almost 6 months old now.
