### ISSUE TITLE
Support for RTX Remix

### ISSUE THREAD

**Issue by CyberAP** [SpecialKO/SpecialK#78]
Just by glancing at the code I assumed SpecialK uses Vulkan as the rendering backend. It would be nice to have an option to enable RTX via [DXVK-remix](https://github.com/NVIDIAGameWorks/dxvk-remix/) (if that's even possible).

**Comment by Aemony** [comment]
Special K does not support Vulkan as a rendering backend. Only reason it works in some Vulkan games is because Nvidia’s D3D11 or AMD’s D3D12 interop layers engage, which SK hooks and plays around with.

Basically the whole thing gets rendered in Vulkan, which SK does not touch, then it gets presented using DXGI (D3D11/D3D12) which SK can and does touch.
